### ISSUE TITLE
Is Pixate Freestyle Abandonware?

### ISSUE THREAD

**Issue by cliftonlabrum** [Pixate/pixate-freestyle-ios#171]
Sorry to ask such a charged question, but it seems development on Freestyle is coming to a standstill. I realize that it's open source, but there doesn't seem to be very many people contributing to it, so I worry about using it over the long-term.

Thoughts?

**Comment by pcolton** [comment]
It's been part of the current Pixate iOS and Android apps since we launched those apps. It's been very stable for us and we've left it up to the community to continue the development. I am looking into how we can simplify version 3 as well as rewriting much of it in Swift (for iOS). We don't have a lot of time to spend on it right now, but it hasn't been forgotten, and it's definitely in the plan to work on it more.
